define_story_outline:
  description: >
    Develop the title, theme, tone, and overall story structure for the book. Begin by analyzing the desired goals for the book and the intended audience (3rd graders). Create a clear and engaging storyline that includes a beginning, middle, and end.

    When defining the story outline, consider the following key points:
    Ensure the tone is consistent with the theme (e.g., adventurous, humorous).
    Incorporate a moral or educational lesson suitable for 3rd graders.
    Provide a logical progression of events with clear transitions between scenes.

    The structure you create should serve as a foundation for character development, scene writing, and illustrations.

  expected_output: >
    A detailed story outline including a suggested title, theme, tone, and a scene-by-scene breakdown.
  agent: Story_Outline_Agent

draft_scene_descriptions:
  description: >
    Write sensory-rich and engaging scene descriptions that align with the story's tone and theme. Include key narrative elements that guide the illustrator in creating dynamic visuals.

    When drafting descriptions, consider the following key points:

    Ensure the scenes provide visual cues for illustrations.
    Maintain a cohesive flow between scenes, as outlined in the story structure.
    Use language that is vivid but accessible to 3rd graders.
  expected_output: >
    A set of scene descriptions, with enough detail to inspire illustrations and ensure narrative consistency.
  agent: Scene_Description_Agent
  
simplify_language:
  description: >
    Review the story text to ensure it is age-appropriate, engaging, and accessible for 3rd graders. Simplify complex words and phrases while retaining the narrative’s tone and depth.

    When simplifying language, consider the following key points:

    Ensure readability for an 8-9 year-old audience.
    Maintain the emotional resonance and thematic integrity of the text.
    Replace difficult vocabulary with simpler alternatives without oversimplifying the meaning.
  expected_output: >
    A simplified version of the story text that aligns with the target audience's reading level.
  agent: Language_Simplification_Agent
  